name: YABA interface tests

on:
  pull_request:
    branches: [ master ]

jobs:
  interface_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: interface

    strategy:
      matrix:
        node-version: [16.x, 17.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.7.0

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.5.2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run the tests and generate coverage report
        run: npm test -- --coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3.1.1
