---
name: YABA Code Linter

on:
  pull_request:
    branches: [master]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2.7.0
        
      - name: Lint Code Base
        uses: github/super-linter@v4.10.1
        env:
          PYTHON_PYLINT_CONFIG_FILE: .pylintrc
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
