name: YABA Code Linter

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: "master"
          PYTHON_PYLINT_CONFIG_FILE: .pylintrc
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
