# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: YABA app and client tests

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  py_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        code: [ app, client]
        include:
          - code: app
            path: ./yaba_test/test_yaba.py
          - code: client
            path: ./yaba_client_test/test_yaba_client.py

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
              pip install --upgrade pip
              pip install pytest pytest-cov
              pip install docker-compose

      - name: Set-up the project
        run: |
              docker-compose -p bety up -d postgres
              docker run --rm --network bety_bety pecan/db

      - name: Test with pytest and generate coverage report
        run: |
              sleep 120
              pytest --cov= ${{ matrix.path }} --cov-report=xml
      
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
